# ===============================
# CONFIGURACIÓN DE BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/itam_db
spring.datasource.username=postgres
spring.datasource.password=IAMtheBesT12!
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar el SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true